theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true
  breadcrumb:
    position: hero-start
    footer: 
  menu:
    dropdown:
      linkToLevel1: true 